version: '3'
services:
  jdk:
    build: .
    image: open-jdk15
    container_name: jdk15-env
    ports:
      - 8000:8000
      - 8080:8080
    tty: true
    volumes:
      - ./projects:/home/projects
